rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 8081

#отправка через дистен в очередь
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          output:
            producer:
              deliveryMode: PERSISTENT
      bindings:
        output:
          group: amqpQueue
          destination: amqpExchange
          content-type: application/json
  datasource:
    embedded-database-connection:


messenger: "cloudStream"




#Жизнь очереди после перезагрузки кролика
mes-queue-config:
  queue:
    durable: true
  message:
    persistent: true

#В текущей реализации можно выбирать только одного отправителя
#messenger: "cloudStream"